package com.abs.cmn.seq;

public enum TEST_CODE {
//	BRS_TRACK_IN_CNFM_REQ,	// 메시지룰 1	1,2,3 케이스 필요
//	BRS_TRACK_IN_REQ,		// 메시지룰 2	1,2,3 케이스 필요
//	WFS_CARR_ID_READ,		// 메시지룰 3	1,2,3 케이스 필요
//	WFS_CARR_ID_READ_01,
//	WFS_SLOTMAP_REPORT,		// 메시지룰 4	1,2,3 케이스 필요
//	WFS_SLOTMAP_REPORT_01,
	
    PARSING_MSG_TO_WFS_01,
    PARSING_MSG_TO_WFS_02,
    PARSING_MSG_TO_WFS_03,
    PARSING_MSG_TO_WFS_04,
    PARSING_MSG_TO_WFS_05,
    PARSING_MSG_TO_WFS_06,
    PARSING_MSG_TO_WFS_07,
    PARSING_MSG_TO_WFS_08,
    PARSING_MSG_TO_WFS_09,
    PARSING_MSG_TO_WFS_10,
    PARSING_MSG_TO_WFS_11,
    PARSING_MSG_TO_WFS_12,
    PARSING_MSG_TO_WFS_13,
    PARSING_MSG_TO_WFS_14,
	
    PARSING_MSG_TO_BRS_01,
    PARSING_MSG_TO_BRS_02,
    PARSING_MSG_TO_BRS_03,
    PARSING_MSG_TO_BRS_04,
    PARSING_MSG_TO_BRS_05,
    PARSING_MSG_TO_BRS_06,
    PARSING_MSG_TO_BRS_07,
    PARSING_MSG_TO_BRS_08,
    PARSING_MSG_TO_BRS_09,
    PARSING_MSG_TO_BRS_10,
    PARSING_MSG_TO_BRS_11,
    PARSING_MSG_TO_BRS_12,
    PARSING_MSG_TO_BRS_13,
    PARSING_MSG_TO_BRS_14,
    
//    PARSING_MSG_TO_EAP_01,
//    PARSING_MSG_TO_EAP_02,
//    
//    PARSING_MSG_TO_MCS,
//    PARSING_MSG_TO_FDC,
//    PARSING_MSG_TO_SPC,
//    PARSING_MSG_TO_RMS,
//    PARSING_MSG_TO_RTD,
//    PARSING_MSG_TO_CRS,
//    PARSING_MSG_TO_MSS
    
    ;
}
